primitives.intervals = [
    { name: 'U',    semitones: 0,   steps: 0 },
    { name: 'm2',   semitones: 1,   steps: 1 },
    { name: 'M2',   semitones: 2,   steps: 1 },
    { name: 'A2',   semitones: 3,   steps: 1 },
    { name: 'd3',   semitones: 2,   steps: 2 },
    { name: 'm3',   semitones: 3,   steps: 2 },
    { name: 'M3',   semitones: 4,   steps: 2 },
    { name: 'd4',   semitones: 4,   steps: 3 },
    { name: 'P4',   semitones: 5,   steps: 3 },
    { name: 'A4',   semitones: 6,   steps: 3 },
    { name: 'd5',   semitones: 6,   steps: 4 },
    { name: 'P5',   semitones: 7,   steps: 4 },
    { name: 'A5',   semitones: 8,   steps: 4 },
    { name: 'm6',   semitones: 8,   steps: 5 },
    { name: 'M6',   semitones: 9,   steps: 5 },
    { name: 'A6',   semitones: 10,  steps: 5 },
    { name: 'd7',   semitones: 9,   steps: 6 },
    { name: 'm7',   semitones: 10,  steps: 6 },
    { name: 'M7',   semitones: 11,  steps: 6 },
    { name: 'P8',   semitones: 12,  steps: 7 },

    { name: 'm9',   semitones: 13,  steps: 8 },
    { name: 'M9',   semitones: 14,  steps: 8 },
    { name: 'A9',   semitones: 15,  steps: 8 },
    { name: 'd11',  semitones: 16,  steps: 10 },
    { name: 'P11',  semitones: 17,  steps: 10 },
    { name: 'A11',  semitones: 18,  steps: 10 },
    { name: 'm13',  semitones: 20,  steps: 12 },
    { name: 'M13',  semitones: 21,  steps: 12 },
    { name: 'A13',  semitones: 22,  steps: 12 }
];